### ISSUE TITLE
prediction of libraries: --threads

### ISSUE THREAD

**Issue by KlemensFroehlich** [vdemichev/DiaNN#82] opened 2021-02-11 16:19 UTC
Hello,
I am new to using DIA-NN and want to predict a library from ~ 1GB FASTAs 
Neither in GUI nor in command line the --thread option seems to influence how many cores the prediction is using.
Is this normal or can the prediction not be parallelized?

As it is now, it takes up to 4000 min to get through 1 FASTA.

Appreciate the great work you are doing!

Best, Klemens

**Comment by vdemichev** [comment] 2021-02-11 16:23
Hi Klemens,

Please use --threads instead of --thread.
Also, if you have a modern CPU, this would speed up things considerably: the prediction algorithm really likes new instruction sets like AVX2 and AVX512.

Vadim

**Comment by vdemichev** [comment] 2021-02-11 16:25
Also, prediction from smaller chunks (say, several million precursor each) might work somewhat faster. With time, Pytorch, which DIA-NN uses for this, seems to fragment the memory, and it leads to a slowdown.

**Comment by KlemensFroehlich** [comment] 2021-02-11 16:44
Hi Vadim,
Thanks for the quick answer. I miswrote. I am already using the --threads command and it does not matter whether I use the GUI and set 5 or 50 or whether I use the command prompt and use --threads 5 or --threads 50

**Comment by KlemensFroehlich** [comment] 2021-02-11 16:45
![image](https://user-images.githubusercontent.com/22170937/107668418-efd90600-6c90-11eb-99c6-80481fb3a861.png)

**Comment by vdemichev** [comment] 2021-02-11 16:49
Please don't set the thread number to values higher than logical cores you have (and better to stick to the number of physical cores actually). Why do you think it does not work, how does it manifest?

**Comment by vdemichev** [comment] 2021-02-11 16:50
If you mean speed is not much higher, then memory fragmentation for the huge database might be an issue. If you run it on a regular =size database (e.g. it's 5 million for human with default settings), then having more threads will definitely help.

**Comment by KlemensFroehlich** [comment] 2021-02-11 16:57
sorry was just for demonstration that I set it to 50. I also tried with 36 in the past.
My server has 48 logical cores with hyperthreading so it should be 96 theoretical cores (sorry again, not an expert)
no matter how high I set the number in the task manager the CPU load of the DIA-NN job is always between ~ 1.4% and 2%

**Comment by KlemensFroehlich** [comment] 2021-02-11 16:58
I also broke down the FASTA into smaller junks (to be more precise I split the FASTA by precursor MZ and let DIA-NN predict multiple libraries.
I looked at the logs and here is what I see:
y is time elapsed in minutes
x is precursor for which prediction was performed
![image](https://user-images.githubusercontent.com/22170937/107670182-c4571b00-6c92-11eb-808c-6e831f6e7204.png)

**Comment by KlemensFroehlich** [comment] 2021-02-11 17:01
for me the increase in computation time (up to 10Mio precursors) seems to be roughly linear to the number of precursors

I even found a bigger prediction analysis which I did and this holds true even for 16 Mio precursors.....

**Comment by vdemichev** [comment] 2021-02-11 17:03
Yes, 300 min for 2 million is not normal at all. I've never seen anything like this. If you wish, email me and I will send you a development version, maybe the issue is resolved in it.

**Comment by KlemensFroehlich** [comment] 2021-02-11 17:31
sent an email

**Comment by KlemensFroehlich** [comment] 2021-02-11 19:01
not sure yet. But I think it might be a challenge with the nature of the peptides for which I want prediction actually.
I just ran a normal HUMAN FASTA from Uniprot and the ~3 Mio precursors ran through in under 30min
The FASTA I am using is a semi-tryptic one, N-terminally and C-terminally ragged to be precise. 
Do you think it could be the FASTA (the headers for example) or the nature of the sequences themselves?

**Comment by vdemichev** [comment] 2021-02-11 19:04
30 min for 3 million is also not normal. The speed should be about 3-4 minutes per million on a 14-core Intel. Since you have a lot more powerful CPU, it should be even higher. No idea what's happening, maybe some Windows settings, hope the beta version works better.

**Comment by KlemensFroehlich** [comment] 2021-02-11 19:37
okay the new version shows the same behaviour on 2 machines: only one core (definitely not as many as I set in the GUI ) are being used for the prediction of my semi-tryptic FASTA (CPU during SPECTRA PREDICTION AND IM at 1.4%).
Here is the interesting part: when I use a normal FASTA (human) and go for tryptic digest and prediction the CPU load is as high as expected (50% on the XEON machine when I use 48 threads)
I now increased the mass range, missed cleavages and variable modifications to get a high number of precursors (17 Mio), still using the "standard" human FASTA and the CPU usage is again at 50% where I would expect it to be. I will write how long the prediction took, as soon as it is done.

I would say it is a problem with my self made semi-tryptic FASTA?

I created it with DBtoolskit, so the headers look a little funny and the sequences can of course be quite short / long:

![image](https://user-images.githubusercontent.com/22170937/107689104-b90eea00-6ca8-11eb-86d5-fc0941293970.png)

**Comment by vdemichev** [comment] 2021-02-11 19:41
Could it be that prediction is fine and DIA-NN just takes ages to load the FASTA? Loading FASTA is single-CPU.

**Comment by KlemensFroehlich** [comment] 2021-02-11 19:50
i dont think so
here the 16 mio precursor prediction i mentioned above
![image](https://user-images.githubusercontent.com/22170937/107690743-cd53e680-6caa-11eb-89e8-3f68ae51619d.png)

**Comment by vdemichev** [comment] 2021-02-11 19:53
Yes, I see... Can you maybe upload the FASTA file somewhere, I will try it on my PC, maybe it's easy to fix the problem. Many thanks for letting me know about this.

**Comment by KlemensFroehlich** [comment] 2021-02-11 19:56
shared it via drive with your email adress. 
the small FASTA is going super quick and the big one is slow during prediction

**Comment by KlemensFroehlich** [comment] 2021-02-12 08:24
Hi Vadim,
Thank you again for looking into this and the great work with DIA-NN!

Just a last update: 
When I search a normal human FASTA and go for 2 missed cleavages, variable modifications and higher precursor mz window, I end up with 17 Mio precursors (many longer ones now though).
These need  ~300min to predict on 48 threads of the XEON server described above. CPU load was 50%, as expected (using the new DIA-NN Dev Version)

Best, Klemens

**Closed** 2021-02-17 10:35 UTC
